### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sisisin** [sisisin/easy-menu-go#1]
- cli option
  - [x] --version
  - [x] --config
  - [x] --help
- [x] work_dir option
- [x] env option
- [x] release binary
- ui
  - [ ] display host name, user name
  - [ ] eval
  - [ ] y/n省略
- [x] unit test
- [ ] validation(map value)
- [x] config file look up
- [ ] documentation
